from regression_tests import *

class TestBase(Test):
    def test_produce_expected_output(self):
        self.assert_c_produces_output_when_run(
            input='1  1',
            expected_output='ackerman( 1 , 1 ) = 3\n',
            expected_return_code=3
        )
        self.assert_c_produces_output_when_run(
            input='2  23  1',
            expected_output='ackerman( 2 , 23 ) = 49\n',
            expected_return_code=49
        )
        self.assert_c_produces_output_when_run(
            input='0       0',
            expected_output='ackerman( 0 , 0 ) = 1\n',
            expected_return_code=1
        )

class Test_2017(TestBase):
    settings_2017 = CriticalTestSettings(
        input=files_in_dir('2017-11-14'),
    )

class Test_2015_ArmClangElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.arm.clang-3.2.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x844c:\s*0d 20 a0 e1\s*mov r2, sp')
        assert self.out_dsm.contains('0x85e4:\s*08 00 8d e5\s*str r0, \[sp, \#8\]')
        assert self.out_dsm.contains('0x8694:\s*10 10 1b e5\s*ldr r1, \[fp, \#\-0x10\]')

class Test_2015_MipsClangElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.mips.clang-3.2.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x4004ec:\s*af bc 00 10\s*sw \$gp, 0x10\(\$sp\)')
        assert self.out_dsm.contains('0x4005e4:\s*24 84 0b 14\s*addiu \$a0, \$a0, 0xb14')
        assert self.out_dsm.contains('0x4008f8:\s*00 12 90 83\s*sra \$s2, \$s2, 2')

class Test_2015_PowerpcGccElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.powerpc.gcc-4.5.1.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x100003ac:\s*93 a1 00 14\s*stw r29, 0x14\(r1\)')
        assert self.out_dsm.contains('0x1000047c:\s*38 09 00 00\s*addi r0, r9, 0')
        assert self.out_dsm.contains('0x10000548:\s*7c 60 1b 78\s*mr r0, r3')

class Test_2015_ThumbClangElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.thumb.clang-3.2.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x8458:\s*10 c0 9f e5\s*ldr ip, \[pc, \#0x10\]')
        assert self.out_dsm.contains('0x8500:\s*08 80 bd 08\s*popeq \{r3, pc\}')
        assert self.out_dsm.contains('0x85a8:\s*06 98\s*ldr r0, \[sp, \#0x18\]')

class Test_2015_X86ClangElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.x86.clang-3.2.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x8048479:\s*89 44 24 04\s*mov dword ptr \[esp \+ 4\], eax')
        assert self.out_dsm.contains('0x80484f0:\s*a1 24 98 04 08\s*mov eax, dword ptr \[0x8049824\]')
        assert self.out_dsm.contains('0x8048699:\s*29 c6\s*sub esi, eax')

class Test_2015_X86GccElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.x86.gcc-4.7.2.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x8048420:\s*b8 03 99 04 08\s*mov eax, 0x8049903')
        assert self.out_dsm.contains('0x804853c:\s*c7 44 24 04 01 00 00 00\s*mov dword ptr \[esp \+ 4\], 1')
        assert self.out_dsm.contains('0x804864b:\s*ff 94 bb 18 ff ff ff\s*call dword ptr \[ebx \+ edi\*4 \- 0xe8\]')

    def test_check_for_tmp_variable_address_in_output_c(self):
        assert self.out_c.contains('result = ack\(x, y\); // 0x80485c3')

class Test_2015_ThumbGccElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.thumb.gnuarmgcc-4.4.1.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x8100:\s*0b 78\s*ldrb r3, \[r1\]')
        assert self.out_dsm.contains('0x81e0:\s*bd 46\s*mov sp, r7')
        assert self.out_dsm.contains('0xe1e2:\s*18 43\s*orrs r0, r3')

    def test_statically_linked_function_detection(self):
        # confirmed functions
        assert self.out_config.is_statically_linked('atexit', 0x8240)
        assert self.out_config.is_statically_linked('exit', 0x8250)
        assert self.out_config.is_statically_linked('__libc_fini_array', 0x8278)
        assert self.out_config.is_statically_linked('__libc_init_array', 0x82a4)
        assert self.out_config.is_statically_linked('memset', 0x82f4)
        assert self.out_config.is_statically_linked('printf', 0x8384)
        assert self.out_config.is_statically_linked('_printf_r', 0x83a8)
        assert self.out_config.is_statically_linked('_scanf_r', 0x83c4)
        assert self.out_config.is_statically_linked('scanf', 0x83e0)
        assert self.out_config.is_statically_linked('initialise_monitor_handles', 0x8404)
        assert self.out_config.is_statically_linked('_kill', 0x8478)
        assert self.out_config.is_statically_linked('_exit', 0x84a4)
        assert self.out_config.is_statically_linked('_gettimeofday', 0x84c8)
        assert self.out_config.is_statically_linked('_times', 0x84f0)
        assert self.out_config.is_statically_linked('error', 0x8510)
        assert self.out_config.is_statically_linked('_rename', 0x852c)
        assert self.out_config.is_statically_linked('_system', 0x8570)
        assert self.out_config.is_statically_linked('_unlink', 0x85c0)
        assert self.out_config.is_statically_linked('_swiopen', 0x85f8)
        assert self.out_config.is_statically_linked('_open', 0x8680)
        assert self.out_config.is_statically_linked('_sbrk', 0x869c)
        assert self.out_config.is_statically_linked('remap_handle', 0x86d0)
        assert self.out_config.is_statically_linked('_isatty', 0x8714)
        assert self.out_config.is_statically_linked('_swiclose', 0x8740)
        assert self.out_config.is_statically_linked('_close', 0x8784)
        assert self.out_config.is_statically_linked('_swiwrite', 0x8798)
        assert self.out_config.is_statically_linked('_write', 0x87bc)
        assert self.out_config.is_statically_linked('_swilseek', 0x881c)
        assert self.out_config.is_statically_linked('_lseek', 0x88ac)
        assert self.out_config.is_statically_linked('_swiread', 0x88c0)
        assert self.out_config.is_statically_linked('_read', 0x88e4)
        assert self.out_config.is_statically_linked('_stat', 0x8940)
        assert self.out_config.is_statically_linked('_fstat', 0x8978)
        assert self.out_config.is_statically_linked('__sprint_r', 0x8998)
        assert self.out_config.is_statically_linked('_vfprintf_r', 0x89b4)
        assert self.out_config.is_statically_linked('vfprintf', 0x9e9c)
        assert self.out_config.is_statically_linked('__svfscanf_r', 0x9eb8)
        assert self.out_config.is_statically_linked('__svfscanf', 0xac84)
        assert self.out_config.is_statically_linked('_vfscanf_r', 0xaca0)
        assert self.out_config.is_statically_linked('vfscanf', 0xacc8)
        assert self.out_config.is_statically_linked('__swsetup_r', 0xacf8)
        assert self.out_config.is_statically_linked('__register_exitproc', 0xadc4)
        assert self.out_config.is_statically_linked('__call_exitprocs', 0xae74)
        assert self.out_config.is_statically_linked('quorem', 0xaf70)
        assert self.out_config.is_statically_linked('_dtoa_r', 0xb0cc)
        assert self.out_config.is_statically_linked('_fflush_r', 0xbfa0)
        assert self.out_config.is_statically_linked('fflush', 0xc0b0)
        assert self.out_config.is_statically_linked('__fp_unlock_all', 0xc0f8)
        assert self.out_config.is_statically_linked('__fp_lock_all', 0xc110)
        assert self.out_config.is_statically_linked('_cleanup_r', 0xc128)
        assert self.out_config.is_statically_linked('_cleanup', 0xc138)
        assert self.out_config.is_statically_linked('std', 0xc148)
        assert self.out_config.is_statically_linked('__sinit', 0xc190)
        assert self.out_config.is_statically_linked('__sfmoreglue', 0xc1e8)
        assert self.out_config.is_statically_linked('__sfp', 0xc214)
        assert self.out_config.is_statically_linked('_fread_r', 0xc2a0)
        assert self.out_config.is_statically_linked('fread', 0xc410)
        assert self.out_config.is_statically_linked('_malloc_trim_r', 0xc434)
        assert self.out_config.is_statically_linked('_free_r', 0xc4d4)
        assert self.out_config.is_statically_linked('__sfvwrite_r', 0xc67c)
        assert self.out_config.is_statically_linked('_fwalk_reent', 0xc9a0)
        assert self.out_config.is_statically_linked('_fwalk', 0xca00)
        assert self.out_config.is_statically_linked('iswspace', 0xca5c)
        assert self.out_config.is_statically_linked('_setlocale_r', 0xca9c)
        assert self.out_config.is_statically_linked('setlocale', 0xcadc)
        assert self.out_config.is_statically_linked('__smakebuf_r', 0xcaf4)
        assert self.out_config.is_statically_linked('free', 0xcbd4)
        assert self.out_config.is_statically_linked('malloc', 0xcbe8)
        assert self.out_config.is_statically_linked('_malloc_r', 0xcbfc)
        assert self.out_config.is_statically_linked('_mbrtowc_r', 0xd114)
        assert self.out_config.is_statically_linked('mbrtowc', 0xd148)
        assert self.out_config.is_statically_linked('_mbtowc_r', 0xd16c)
        assert self.out_config.is_statically_linked('memchr', 0xd19c)
        assert self.out_config.is_statically_linked('memcpy', 0xd218)
        assert self.out_config.is_statically_linked('memmove', 0xd294)
        assert self.out_config.is_statically_linked('_Bfree', 0xd338)
        assert self.out_config.is_statically_linked('__hi0bits', 0xd34c)
        assert self.out_config.is_statically_linked('__lo0bits', 0xd394)
        assert self.out_config.is_statically_linked('__mcmp', 0xd3f8)
        assert self.out_config.is_statically_linked('__ulp', 0xd434)
        assert self.out_config.is_statically_linked('__b2d', 0xd484)
        assert self.out_config.is_statically_linked('__ratio', 0xd52c)
        assert self.out_config.is_statically_linked('_mprec_log10', 0xd58c)
        assert self.out_config.is_statically_linked('__copybits', 0xd5c8)
        assert self.out_config.is_statically_linked('__any_on', 0xd60c)
        assert self.out_config.is_statically_linked('_Balloc', 0xd654)
        assert self.out_config.is_statically_linked('__d2b', 0xd6a4)
        assert self.out_config.is_statically_linked('__mdiff', 0xd780)
        assert self.out_config.is_statically_linked('__lshift', 0xd890)
        assert self.out_config.is_statically_linked('__multiply', 0xd94c)
        assert self.out_config.is_statically_linked('__i2b', 0xdaa8)
        assert self.out_config.is_statically_linked('__multadd', 0xdabc)
        assert self.out_config.is_statically_linked('__pow5mult', 0xdb58)
        assert self.out_config.is_statically_linked('__s2b', 0xdc0c)
        assert self.out_config.is_statically_linked('_realloc_r', 0xdca4)
        assert self.out_config.is_statically_linked('__srefill_r', 0xdff4)
        assert self.out_config.is_statically_linked('lflush', 0xe0fc)
        assert self.out_config.is_statically_linked('_sbrk_r', 0xe114)
        assert self.out_config.is_statically_linked('__sccl', 0xe138)
        assert self.out_config.is_statically_linked('isinf', 0xe1b4)
        assert self.out_config.is_statically_linked('__isnand', 0xe1d8)
        assert self.out_config.is_statically_linked('sprintf', 0xe1f4)
        assert self.out_config.is_statically_linked('_sprintf_r', 0xe238)
        assert self.out_config.is_statically_linked('__sseek', 0xe284)
        assert self.out_config.is_statically_linked('__swrite', 0xe2b0)
        assert self.out_config.is_statically_linked('__sread', 0xe2e8)
        assert self.out_config.is_statically_linked('strcmp', 0xe310)
        assert self.out_config.is_statically_linked('strlen', 0xe368)
        assert self.out_config.is_statically_linked('_strtod_r', 0xe3d0)
        assert self.out_config.is_statically_linked('strtof', 0xf258)
        assert self.out_config.is_statically_linked('strtod', 0xf28c)
        assert self.out_config.is_statically_linked('_strtol_r', 0xf2a4)
        assert self.out_config.is_statically_linked('strtol', 0xf410)
        assert self.out_config.is_statically_linked('_strtoul_r', 0xf42c)
        assert self.out_config.is_statically_linked('strtoul', 0xf584)
        assert self.out_config.is_statically_linked('__sprint_r', 0xf5a0)
        assert self.out_config.is_statically_linked('_svfprintf_r', 0xf6d0)
        assert self.out_config.is_statically_linked('__submore', 0x109dc)
        assert self.out_config.is_statically_linked('_ungetc_r', 0x10a54)
        assert self.out_config.is_statically_linked('ungetc', 0x10b58)
        assert self.out_config.is_statically_linked('_write_r', 0x10b70)
        assert self.out_config.is_statically_linked('_calloc_r', 0x10b98)
        assert self.out_config.is_statically_linked('_close_r', 0x10bf0)
        assert self.out_config.is_statically_linked('_fclose_r', 0x10c14)
        assert self.out_config.is_statically_linked('fclose', 0x10cb4)
        assert self.out_config.is_statically_linked('_fstat_r', 0x10ccc)
        assert self.out_config.is_statically_linked('__hexdig_init', 0x10cf4)
        assert self.out_config.is_statically_linked('rshift', 0x10d4c)
        assert self.out_config.is_statically_linked('__gethex', 0x10dec)
        assert self.out_config.is_statically_linked('__hexnan', 0x1128c)
        assert self.out_config.is_statically_linked('_isatty_r', 0x11440)
        assert self.out_config.is_statically_linked('_lseek_r', 0x11464)
        assert self.out_config.is_statically_linked('_read_r', 0x1148c)
        assert self.out_config.is_statically_linked('_wrapup_reent', 0x114b4)
        assert self.out_config.is_statically_linked('cleanup_glue', 0x114fc)
        assert self.out_config.is_statically_linked('_reclaim_reent', 0x11518)
        # leftovers - unconfirmed

class Test_2015_ArmGccElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.arm.gnuarmgcc-4.4.1.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x8084:\s*01 30 a0 e3\s*mov r3, \#1')
        assert self.out_dsm.contains('0x8214:\s*ff 00 00 00\s*strdeq r0, r1, \[r0\], \-pc')
        assert self.out_dsm.contains('0x81c4:\s*04 40 12 85\s*ldrhi r4, \[r2, \#\-4\]')

    def test_statically_linked_function_detection(self):
        # confirmed functions
        assert self.out_config.is_statically_linked('atexit', 0x833c)
        assert self.out_config.is_statically_linked('exit', 0x8350)
        assert self.out_config.is_statically_linked('__libc_fini_array', 0x8380)
        assert self.out_config.is_statically_linked('__libc_init_array', 0x83c0)
        assert self.out_config.is_statically_linked('memset', 0x8434)
        assert self.out_config.is_statically_linked('printf', 0x852c)
        assert self.out_config.is_statically_linked('_printf_r', 0x856c)
        assert self.out_config.is_statically_linked('_scanf_r', 0x85a0)
        assert self.out_config.is_statically_linked('scanf', 0x85d4)
        assert self.out_config.is_statically_linked('initialise_monitor_handles', 0x8614)
        assert self.out_config.is_statically_linked('_kill', 0x86c0)
        assert self.out_config.is_statically_linked('_exit', 0x8714)
        assert self.out_config.is_statically_linked('_gettimeofday', 0x8748)
        assert self.out_config.is_statically_linked('_times', 0x878c)
        assert self.out_config.is_statically_linked('error', 0x87c8)
        assert self.out_config.is_statically_linked('_rename', 0x87fc)
        assert self.out_config.is_statically_linked('_system', 0x8868)
        assert self.out_config.is_statically_linked('_unlink', 0x88f4)
        assert self.out_config.is_statically_linked('_swiopen', 0x894c)
        assert self.out_config.is_statically_linked('_open', 0x8a1c)
        assert self.out_config.is_statically_linked('_sbrk', 0x8a54)
        assert self.out_config.is_statically_linked('remap_handle', 0x8aa8)
        assert self.out_config.is_statically_linked('_isatty', 0x8b1c)
        assert self.out_config.is_statically_linked('_swiclose', 0x8b68)
        assert self.out_config.is_statically_linked('_close', 0x8bdc)
        assert self.out_config.is_statically_linked('_swiwrite', 0x8bf4)
        assert self.out_config.is_statically_linked('_write', 0x8c30)
        assert self.out_config.is_statically_linked('_swilseek', 0x8cbc)
        assert self.out_config.is_statically_linked('_lseek', 0x8dac)
        assert self.out_config.is_statically_linked('_swiread', 0x8dc4)
        assert self.out_config.is_statically_linked('_read', 0x8e00)
        assert self.out_config.is_statically_linked('_stat', 0x8e88)
        assert self.out_config.is_statically_linked('_fstat', 0x8ed4)
        assert self.out_config.is_statically_linked('__sprint_r', 0x8f04)
        assert self.out_config.is_statically_linked('_vfprintf_r', 0x8f34)
        assert self.out_config.is_statically_linked('vfprintf', 0xae80)
        assert self.out_config.is_statically_linked('__svfscanf_r', 0xaeac)
        assert self.out_config.is_statically_linked('__svfscanf', 0xc234)
        assert self.out_config.is_statically_linked('_vfscanf_r', 0xc260)
        assert self.out_config.is_statically_linked('vfscanf', 0xc2a8)
        assert self.out_config.is_statically_linked('__swsetup_r', 0xc2fc)
        assert self.out_config.is_statically_linked('__register_exitproc', 0xc444)
        assert self.out_config.is_statically_linked('__call_exitprocs', 0xc528)
        assert self.out_config.is_statically_linked('quorem', 0xc670)
        assert self.out_config.is_statically_linked('_dtoa_r', 0xc850)
        assert self.out_config.is_statically_linked('__errno', 0xde34)
        assert self.out_config.is_statically_linked('_fflush_r', 0xde44)
        assert self.out_config.is_statically_linked('fflush', 0xe010)
        assert self.out_config.is_statically_linked('__fp_lock_all', 0xe060)
        assert self.out_config.is_statically_linked('__fp_unlock_all', 0xe078)
        assert self.out_config.is_statically_linked('_cleanup', 0xe09c)
        assert self.out_config.is_statically_linked('std', 0xe0ac)
        assert self.out_config.is_statically_linked('__sinit', 0xe124)
        assert self.out_config.is_statically_linked('__sfmoreglue', 0xe1a0)
        assert self.out_config.is_statically_linked('__sfp', 0xe1e4)
        assert self.out_config.is_statically_linked('_fread_r', 0xe2d4)
        assert self.out_config.is_statically_linked('fread', 0xe4f8)
        assert self.out_config.is_statically_linked('_malloc_trim_r', 0xe538)
        assert self.out_config.is_statically_linked('_free_r', 0xe630)
        assert self.out_config.is_statically_linked('__sfvwrite_r', 0xe8a4)
        assert self.out_config.is_statically_linked('_fwalk_reent', 0xed48)
        assert self.out_config.is_statically_linked('_fwalk', 0xedcc)
        assert self.out_config.is_statically_linked('iswspace', 0xee4c)
        assert self.out_config.is_statically_linked('__getreent', 0xee70)
        assert self.out_config.is_statically_linked('_setlocale_r', 0xee98)
        assert self.out_config.is_statically_linked('setlocale', 0xeef8)
        assert self.out_config.is_statically_linked('__smakebuf_r', 0xef14)
        assert self.out_config.is_statically_linked('free', 0xf074)
        assert self.out_config.is_statically_linked('malloc', 0xf088)
        assert self.out_config.is_statically_linked('_malloc_r', 0xf09c)
        assert self.out_config.is_statically_linked('_mbrtowc_r', 0xf7d0)
        assert self.out_config.is_statically_linked('mbrtowc', 0xf828)
        assert self.out_config.is_statically_linked('_mbtowc_r', 0xf868)
        assert self.out_config.is_statically_linked('memchr', 0xf8b8)
        assert self.out_config.is_statically_linked('memcpy', 0xf98c)
        assert self.out_config.is_statically_linked('memmove', 0xfa7c)
        assert self.out_config.is_statically_linked('_Bfree', 0xfbb0)
        assert self.out_config.is_statically_linked('__hi0bits', 0xfbcc)
        assert self.out_config.is_statically_linked('__lo0bits', 0xfc24)
        assert self.out_config.is_statically_linked('__mcmp', 0xfcb8)
        assert self.out_config.is_statically_linked('__ulp', 0xfd18)
        assert self.out_config.is_statically_linked('__b2d', 0xfd78)
        assert self.out_config.is_statically_linked('__ratio', 0xfe48)
        assert self.out_config.is_statically_linked('_mprec_log10', 0xfee4)
        assert self.out_config.is_statically_linked('__copybits', 0xff30)
        assert self.out_config.is_statically_linked('__any_on', 0xffac)
        assert self.out_config.is_statically_linked('_Balloc', 0x1002c)
        assert self.out_config.is_statically_linked('__d2b', 0x100b0)
        assert self.out_config.is_statically_linked('__mdiff', 0x101bc)
        assert self.out_config.is_statically_linked('__lshift', 0x10330)
        assert self.out_config.is_statically_linked('__multiply', 0x10440)
        assert self.out_config.is_statically_linked('__i2b', 0x10630)
        assert self.out_config.is_statically_linked('__multadd', 0x10650)
        assert self.out_config.is_statically_linked('__pow5mult', 0x10730)
        assert self.out_config.is_statically_linked('__s2b', 0x10828)
        assert self.out_config.is_statically_linked('_realloc_r', 0x1090c)
        assert self.out_config.is_statically_linked('__srefill_r', 0x10e00)
        assert self.out_config.is_statically_linked('lflush', 0x10fac)
        assert self.out_config.is_statically_linked('_sbrk_r', 0x10fc8)
        assert self.out_config.is_statically_linked('__sccl', 0x11000)
        assert self.out_config.is_statically_linked('isinf', 0x110cc)
        assert self.out_config.is_statically_linked('__isnand', 0x110fc)
        assert self.out_config.is_statically_linked('sprintf', 0x1112c)
        assert self.out_config.is_statically_linked('_sprintf_r', 0x111a0)
        assert self.out_config.is_statically_linked('__sseek', 0x11210)
        assert self.out_config.is_statically_linked('__swrite', 0x11244)
        assert self.out_config.is_statically_linked('__sread', 0x11298)
        assert self.out_config.is_statically_linked('strcmp', 0x112c8)
        assert self.out_config.is_statically_linked('strlen', 0x113a0)
        assert self.out_config.is_statically_linked('_strtod_r', 0x1143c)
        assert self.out_config.is_statically_linked('strtof', 0x129cc)
        assert self.out_config.is_statically_linked('strtod', 0x12a1c)
        assert self.out_config.is_statically_linked('_strtol_r', 0x12a38)
        assert self.out_config.is_statically_linked('strtol', 0x12bdc)
        assert self.out_config.is_statically_linked('_strtoul_r', 0x12c08)
        assert self.out_config.is_statically_linked('strtoul', 0x12da4)
        assert self.out_config.is_statically_linked('__sprint_r', 0x12dd0)
        assert self.out_config.is_statically_linked('_svfprintf_r', 0x12f54)
        assert self.out_config.is_statically_linked('__submore', 0x14d38)
        assert self.out_config.is_statically_linked('_ungetc_r', 0x14de0)
        assert self.out_config.is_statically_linked('ungetc', 0x14fa0)
        assert self.out_config.is_statically_linked('_write_r', 0x14fbc)
        assert self.out_config.is_statically_linked('_calloc_r', 0x14ffc)
        assert self.out_config.is_statically_linked('_close_r', 0x15098)
        assert self.out_config.is_statically_linked('_fclose_r', 0x150d0)
        assert self.out_config.is_statically_linked('fclose', 0x151c4)
        assert self.out_config.is_statically_linked('_fstat_r', 0x151d8)
        assert self.out_config.is_statically_linked('__hexdig_init', 0x15214)
        assert self.out_config.is_statically_linked('rshift', 0x15298)
        assert self.out_config.is_statically_linked('__gethex', 0x1537c)
        assert self.out_config.is_statically_linked('__hexnan', 0x15a34)
        assert self.out_config.is_statically_linked('_isatty_r', 0x15cc0)
        assert self.out_config.is_statically_linked('_lseek_r', 0x15cf8)
        assert self.out_config.is_statically_linked('_read_r', 0x15d38)
        assert self.out_config.is_statically_linked('_wrapup_reent', 0x15d78)
        assert self.out_config.is_statically_linked('cleanup_glue', 0x15de8)
        assert self.out_config.is_statically_linked('_reclaim_reent', 0x15e10)
        # leftovers - unconfirmed

class Test_2015_ArmGccExe(TestBase):
    settings = TestSettings( input='2015-03-30/ack.arm.mingw32ce-4.4.0.O0.g.ex' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x11004:\s*00 40 a0 e1\s*mov r4, r0')
        assert self.out_dsm.contains('0x11080:\s*10 30 1b e5\s*ldr r3, \[fp, \#\-0x10\]')
        assert self.out_dsm.contains('0x11628:\s*00 b0 a0 11\s*movne fp, r0')

    def test_statically_linked_function_detection(self):
        # confirmed functions
        assert self.out_config.is_statically_linked('_pei386_runtime_relocator', 0x1117c)
        assert self.out_config.is_statically_linked('__atexit_first', 0x111c4)
        assert self.out_config.is_statically_linked('_exit', 0x111d8)
        assert self.out_config.is_statically_linked('__dllonexit', 0x111f4)
        assert self.out_config.is_statically_linked('_onexit', 0x11278)
        assert self.out_config.is_statically_linked('atexit', 0x1128c)
        assert self.out_config.is_statically_linked('__dll_exit', 0x112b4)
        assert self.out_config.is_statically_linked('_cexit', 0x11320)
        assert self.out_config.is_statically_linked('exit', 0x11330)
        assert self.out_config.is_statically_linked('__atexit_init', 0x1134c)
        assert self.out_config.is_statically_linked('__mingw_do_global_dtors', 0x11388)
        assert self.out_config.is_statically_linked('__mingw_do_global_ctors', 0x113c8)
        assert self.out_config.is_statically_linked('__gccmain', 0x11430)
        assert self.out_config.is_statically_linked('WinMain', 0x116a8)
        # leftovers - unconfirmed

class Test_2015_Pic32GccElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.pic32.gcc-4.5.2.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x9d001dac:\s*01 00 05 24\s*addiu \$a1, \$zero, 1')
        assert self.out_dsm.contains('0x9d001e38:\s*00 9d 04 3c\s*lui \$a0, 0x9d00')
        assert self.out_dsm.contains('0x9d001e3c:\s*1c 2c 84 24\s*addiu \$a0, \$a0, 0x2c1c')

    def test_statically_linked_function_detection(self):
        # confirmed functions
        assert self.out_config.is_statically_linked('vfprintf', 0x9d000020)
        assert self.out_config.is_statically_linked('vfscanf', 0x9d000ad0)
        assert self.out_config.is_statically_linked('filbuf', 0x9d001bf4)
        assert self.out_config.is_statically_linked('fputc', 0x9d001ff8)
        assert self.out_config.is_statically_linked('read', 0x9d002138)
        assert self.out_config.is_statically_linked('flsbuf', 0x9d002278)
        assert self.out_config.is_statically_linked('fgetc', 0x9d0023a4)
        assert self.out_config.is_statically_linked('general_exception_context', 0x9d0025b0)
        assert self.out_config.is_statically_linked('mon_putc', 0x9d002750)
        assert self.out_config.is_statically_linked('atoi', 0x9d002804)
        assert self.out_config.is_statically_linked('range', 0x9d0028a4)
        assert self.out_config.is_statically_linked('fflush', 0x9d002934)
        assert self.out_config.is_statically_linked('write', 0x9d0029c4)
        assert self.out_config.is_statically_linked('ungetc', 0x9d002a48)
        assert self.out_config.is_statically_linked('wspace', 0x9d002abc)
        assert self.out_config.is_statically_linked('DefaultInterrupt', 0x9d002b1c)
        assert self.out_config.is_statically_linked('printf', 0x9d002b64)
        assert self.out_config.is_statically_linked('scanf', 0x9d002ba4)
        assert self.out_config.is_statically_linked('tolower', 0x9d002c40)
        assert self.out_config.is_statically_linked('toupper', 0x9d002c64)
        assert self.out_config.is_statically_linked('isalnum', 0x9d002ca0)
        assert self.out_config.is_statically_linked('isalpha', 0x9d002cb8)
        assert self.out_config.is_statically_linked('iscntrl', 0x9d002cd0)
        assert self.out_config.is_statically_linked('isdigit', 0x9d002ce8)
        assert self.out_config.is_statically_linked('isgraph', 0x9d002d00)
        assert self.out_config.is_statically_linked('islower', 0x9d002d18)
        assert self.out_config.is_statically_linked('isprint', 0x9d002d30)
        assert self.out_config.is_statically_linked('ispunct', 0x9d002d48)
        assert self.out_config.is_statically_linked('isspace', 0x9d002d60)
        assert self.out_config.is_statically_linked('isupper', 0x9d002d78)
        assert self.out_config.is_statically_linked('isxdigit', 0x9d002d90)
        # leftovers - unconfirmed
        assert not self.out_config.is_statically_linked('nmi_handler', 0x9d002c88)

class Test_2015_MipsGccElf(TestBase):
    settings = TestSettings( input='2015-03-30/ack.mips.pspgcc-4.3.5.O0.g.elf' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x8900044:\s*00 00 62 24\s*addiu \$v0, \$v1, 0')
        assert self.out_dsm.contains('0x890018c:\s*60 00 b3 af\s*sw \$s3, 0x60\(\$sp\)')
        assert self.out_dsm.contains('0x890026c:\s*ff ff 51 24\s*addiu \$s1, \$v0, -1')

    def test_properties(self):
        assert self.out_c.has_comment_matching('// int printf\(const char \* restrict format, ...\);')
        assert self.out_c.has_comment_matching('// int scanf\(const char \* restrict format, ...\);')
        assert self.out_c.contains('int32_t x = 0; // bp-28')
        assert self.out_c.contains('int32_t y = 0; // bp-24')

    def test_statically_linked_function_detection(self):
        # confirmed functions
        assert self.out_config.is_statically_linked('atexit', 0x89004c0)
        assert self.out_config.is_statically_linked('exit', 0x89004d4)
        assert self.out_config.is_statically_linked('printf', 0x8900510)
        assert self.out_config.is_statically_linked('_printf_r', 0x8900560)
        assert self.out_config.is_statically_linked('_scanf_r', 0x89005a4)
        assert self.out_config.is_statically_linked('scanf', 0x89005e8)
        assert self.out_config.is_statically_linked('strlen', 0x8900638)
        assert self.out_config.is_statically_linked('_vfprintf_r', 0x8900654)
        assert self.out_config.is_statically_linked('vfprintf', 0x8902698)
        assert self.out_config.is_statically_linked('__svfscanf_r', 0x89026b8)
        assert self.out_config.is_statically_linked('__svfscanf', 0x8903a8c)
        assert self.out_config.is_statically_linked('_vfscanf_r', 0x8903aac)
        assert self.out_config.is_statically_linked('vfscanf', 0x8903b18)
        assert self.out_config.is_statically_linked('__swsetup_r', 0x8903b88)
        assert self.out_config.is_statically_linked('sprintf', 0x8903cec)
        assert self.out_config.is_statically_linked('vxprintf', 0x8903d40)
        assert self.out_config.is_statically_linked('__sout', 0x8905348)
        assert self.out_config.is_statically_linked('__psp_libc_init', 0x89053d0)
        assert self.out_config.is_statically_linked('_exit', 0x89053f0)
        assert self.out_config.is_statically_linked('__psp_free_heap', 0x890544c)
        assert self.out_config.is_statically_linked('_sbrk', 0x890546c)
        assert self.out_config.is_statically_linked('__psp_fdman_release_descriptor', 0x89055b0)
        assert self.out_config.is_statically_linked('__psp_fdman_get_dup_descriptor', 0x8905674)
        assert self.out_config.is_statically_linked('__psp_fdman_get_new_descriptor', 0x8905790)
        assert self.out_config.is_statically_linked('__psp_fdman_init', 0x8905848)
        assert self.out_config.is_statically_linked('pspDisableInterrupts', 0x8905920)
        assert self.out_config.is_statically_linked('pspEnableInterrupts', 0x8905984)
        assert self.out_config.is_statically_linked('__register_exitproc', 0x89059e4)
        assert self.out_config.is_statically_linked('__call_exitprocs', 0x8905b28)
        assert self.out_config.is_statically_linked('quorem', 0x8905cb4)
        assert self.out_config.is_statically_linked('_dtoa_r', 0x8905f44)
        assert self.out_config.is_statically_linked('__errno', 0x89075b4)
        assert self.out_config.is_statically_linked('_fflush_r', 0x89075c4)
        assert self.out_config.is_statically_linked('fflush', 0x890784c)
        assert self.out_config.is_statically_linked('__fp_unlock_all', 0x89078ac)
        assert self.out_config.is_statically_linked('__fp_lock_all', 0x89078c4)
        assert self.out_config.is_statically_linked('_cleanup_r', 0x89078dc)
        assert self.out_config.is_statically_linked('_cleanup', 0x89078ec)
        assert self.out_config.is_statically_linked('std', 0x8907904)
        assert self.out_config.is_statically_linked('__sinit', 0x890798c)
        assert self.out_config.is_statically_linked('__sfmoreglue', 0x8907a24)
        assert self.out_config.is_statically_linked('__sfp', 0x8907a90)
        assert self.out_config.is_statically_linked('_fread_r', 0x8907b90)
        assert self.out_config.is_statically_linked('fread', 0x8907eb4)
        assert self.out_config.is_statically_linked('_malloc_trim_r', 0x8907edc)
        assert self.out_config.is_statically_linked('_free_r', 0x8907ffc)
        assert self.out_config.is_statically_linked('_fwalk_reent', 0x89082e0)
        assert self.out_config.is_statically_linked('_fwalk', 0x89083e0)
        assert self.out_config.is_statically_linked('isdigit', 0x89084cc)
        assert self.out_config.is_statically_linked('iswspace', 0x89084e4)
        assert self.out_config.is_statically_linked('__locale_charset', 0x8908510)
        assert self.out_config.is_statically_linked('__locale_msgcharset', 0x8908520)
        assert self.out_config.is_statically_linked('_localeconv_r', 0x8908538)
        assert self.out_config.is_statically_linked('localeconv', 0x8908548)
        assert self.out_config.is_statically_linked('_setlocale_r', 0x8908558)
        assert self.out_config.is_statically_linked('setlocale', 0x89085d4)
        assert self.out_config.is_statically_linked('__smakebuf_r', 0x89085ec)
        assert self.out_config.is_statically_linked('free', 0x890878c)
        assert self.out_config.is_statically_linked('malloc', 0x89087a0)
        assert self.out_config.is_statically_linked('_malloc_r', 0x89087b4)
        assert self.out_config.is_statically_linked('mbrtowc', 0x8908ff0)
        assert self.out_config.is_statically_linked('_mbrtowc_r', 0x8909104)
        assert self.out_config.is_statically_linked('__ascii_mbtowc', 0x8909204)
        assert self.out_config.is_statically_linked('_mbtowc_r', 0x8909240)
        assert self.out_config.is_statically_linked('memchr', 0x89092bc)
        assert self.out_config.is_statically_linked('memcpy', 0x89093bc)
        assert self.out_config.is_statically_linked('memset', 0x890950c)
        assert self.out_config.is_statically_linked('_Bfree', 0x8909608)
        assert self.out_config.is_statically_linked('__hi0bits', 0x8909634)
        assert self.out_config.is_statically_linked('__lo0bits', 0x89096b8)
        assert self.out_config.is_statically_linked('__mcmp', 0x8909788)
        assert self.out_config.is_statically_linked('__ulp', 0x89097f8)
        assert self.out_config.is_statically_linked('__b2d', 0x890986c)
        assert self.out_config.is_statically_linked('__ratio', 0x89099d0)
        assert self.out_config.is_statically_linked('_mprec_log10', 0x8909a94)
        assert self.out_config.is_statically_linked('__copybits', 0x8909b50)
        assert self.out_config.is_statically_linked('__any_on', 0x8909be4)
        assert self.out_config.is_statically_linked('_Balloc', 0x8909c8c)
        assert self.out_config.is_statically_linked('__d2b', 0x8909d3c)
        assert self.out_config.is_statically_linked('__mdiff', 0x8909eb0)
        assert self.out_config.is_statically_linked('__lshift', 0x890a0a8)
        assert self.out_config.is_statically_linked('__multiply', 0x890a21c)
        assert self.out_config.is_statically_linked('__i2b', 0x890a464)
        assert self.out_config.is_statically_linked('__multadd', 0x890a498)
        assert self.out_config.is_statically_linked('__pow5mult', 0x890a5bc)
        assert self.out_config.is_statically_linked('__s2b', 0x890a6f0)
        assert self.out_config.is_statically_linked('__srefill_r', 0x890a82c)
        assert self.out_config.is_statically_linked('lflush', 0x890aa30)
        assert self.out_config.is_statically_linked('__fpclassifyd', 0x890aa54)
        assert self.out_config.is_statically_linked('_sbrk_r', 0x890aafc)
        assert self.out_config.is_statically_linked('__sccl', 0x890ab58)
        assert self.out_config.is_statically_linked('nanf', 0x890ac2c)
        assert self.out_config.is_statically_linked('__sseek', 0x890ac4c)
        assert self.out_config.is_statically_linked('__swrite', 0x890acb4)
        assert self.out_config.is_statically_linked('__sread', 0x890ad34)
        assert self.out_config.is_statically_linked('strcmp', 0x890ad98)
        assert self.out_config.is_statically_linked('_strtod_r', 0x890ae14)
        assert self.out_config.is_statically_linked('strtof', 0x890c4c0)
        assert self.out_config.is_statically_linked('strtod', 0x890c538)
        assert self.out_config.is_statically_linked('_strtol_r', 0x890c550)
        assert self.out_config.is_statically_linked('strtol', 0x890c760)
        assert self.out_config.is_statically_linked('_strtoll_r', 0x890c780)
        assert self.out_config.is_statically_linked('_strtoul_r', 0x890caa8)
        assert self.out_config.is_statically_linked('strtoul', 0x890ccb8)
        assert self.out_config.is_statically_linked('_strtoull_r', 0x890ccd8)
        assert self.out_config.is_statically_linked('__submore', 0x890cffc)
        assert self.out_config.is_statically_linked('_ungetc_r', 0x890d114)
        assert self.out_config.is_statically_linked('ungetc', 0x890d2ec)
        assert self.out_config.is_statically_linked('__sprint_r', 0x890d304)
        assert self.out_config.is_statically_linked('_vfiprintf_r', 0x890d434)
        assert self.out_config.is_statically_linked('vfiprintf', 0x890e524)
        assert self.out_config.is_statically_linked('_write_r', 0x890e544)
        assert self.out_config.is_statically_linked('__psp_get_drive', 0x890e5b4)
        assert self.out_config.is_statically_linked('__psp_safe_strcpy', 0x890e614)
        assert self.out_config.is_statically_linked('__psp_safe_strcat', 0x890e64c)
        assert self.out_config.is_statically_linked('__psp_path_normalize', 0x890e6a0)
        assert self.out_config.is_statically_linked('__psp_path_absolute', 0x890e98c)
        assert self.out_config.is_statically_linked('__psp_init_cwd', 0x890ebec)
        assert self.out_config.is_statically_linked('_write', 0x890ec38)
        assert self.out_config.is_statically_linked('chdir', 0x890ed0c)
        assert self.out_config.is_statically_linked('isatty', 0x890ed98)
        assert self.out_config.is_statically_linked('_isatty_r', 0x890edf8)
        assert self.out_config.is_statically_linked('_calloc_r', 0x890ee70)
        assert self.out_config.is_statically_linked('_close_r', 0x890ef28)
        assert self.out_config.is_statically_linked('_fclose_r', 0x890ef90)
        assert self.out_config.is_statically_linked('fclose', 0x890f0c8)
        assert self.out_config.is_statically_linked('_fputwc_r', 0x890f0dc)
        assert self.out_config.is_statically_linked('fputwc', 0x890f2dc)
        assert self.out_config.is_statically_linked('_fstat_r', 0x890f33c)
        assert self.out_config.is_statically_linked('__sfvwrite_r', 0x890f3a8)
        assert self.out_config.is_statically_linked('__hexdig_init', 0x890f890)
        assert self.out_config.is_statically_linked('rshift', 0x890f924)
        assert self.out_config.is_statically_linked('__gethex', 0x890fa58)
        assert self.out_config.is_statically_linked('__hexnan', 0x89103c8)
        assert self.out_config.is_statically_linked('_lseek_r', 0x89106b0)
        assert self.out_config.is_statically_linked('memmove', 0x8910720)
        assert self.out_config.is_statically_linked('_read_r', 0x8910878)
        assert self.out_config.is_statically_linked('_realloc_r', 0x89108e8)
        assert self.out_config.is_statically_linked('_wrapup_reent', 0x8910ea8)
        assert self.out_config.is_statically_linked('cleanup_glue', 0x8910f64)
        assert self.out_config.is_statically_linked('_reclaim_reent', 0x8910fa8)
        assert self.out_config.is_statically_linked('strcpy', 0x89110d4)
        assert self.out_config.is_statically_linked('strncmp', 0x8911160)
        assert self.out_config.is_statically_linked('strncpy', 0x8911278)
        assert self.out_config.is_statically_linked('strrchr', 0x891145c)
        assert self.out_config.is_statically_linked('__swbuf_r', 0x89114c4)
        assert self.out_config.is_statically_linked('__swbuf', 0x8911634)
        assert self.out_config.is_statically_linked('wcrtomb', 0x891164c)
        assert self.out_config.is_statically_linked('_wcrtomb_r', 0x8911744)
        assert self.out_config.is_statically_linked('__ascii_wctomb', 0x8911828)
        assert self.out_config.is_statically_linked('_wctomb_r', 0x891185c)
        assert self.out_config.is_statically_linked('__psp_pipe_nonblocking_write', 0x89118c8)
        assert self.out_config.is_statically_linked('__psp_pipe_write', 0x8911994)
        assert self.out_config.is_statically_linked('__psp_pipe_read', 0x8911a3c)
        assert self.out_config.is_statically_linked('__psp_pipe_close', 0x8911ae4)
        assert self.out_config.is_statically_linked('pipe', 0x8911ba8)
        assert self.out_config.is_statically_linked('__psp_pipe_peekmsgsize', 0x8911cc4)
        assert self.out_config.is_statically_linked('__psp_pipe_nonblocking_read', 0x8911d48)
        assert self.out_config.is_statically_linked('__psp_set_errno', 0x8911e44)
        assert self.out_config.is_statically_linked('_close', 0x8911e8c)
        assert self.out_config.is_statically_linked('_fstat', 0x8911f8c)
        assert self.out_config.is_statically_linked('_lseek', 0x8912110)
        assert self.out_config.is_statically_linked('_read', 0x8912188)
        assert self.out_config.is_statically_linked('strchr', 0x891225c)
        assert self.out_config.is_statically_linked('stat', 0x8912438)
        assert self.out_config.is_statically_linked('_stat_r', 0x8912450)
        assert self.out_config.is_statically_linked('_stat', 0x89124bc)
        assert self.out_config.is_statically_linked('validate_structure', 0x8912708)
        assert self.out_config.is_statically_linked('mktime', 0x8912a90)
        assert self.out_config.is_statically_linked('__tzcalc_limits', 0x8912e88)
        assert self.out_config.is_statically_linked('_mktm_r', 0x8913104)
        assert self.out_config.is_statically_linked('div', 0x89136a0)
        assert self.out_config.is_statically_linked('__gettzinfo', 0x891371c)
        assert self.out_config.is_statically_linked('__fixunsdfsi', 0x891372c)
        assert self.out_config.is_statically_linked('__udivdi3', 0x89137c0)
        assert self.out_config.is_statically_linked('__umoddi3', 0x8913db8)
        assert self.out_config.is_statically_linked('_fpadd_parts', 0x8914440)
        assert self.out_config.is_statically_linked('__subdf3', 0x89148a8)
        assert self.out_config.is_statically_linked('__adddf3', 0x8914920)
        assert self.out_config.is_statically_linked('__muldf3', 0x891498c)
        assert self.out_config.is_statically_linked('__divdf3', 0x8914c80)
        assert self.out_config.is_statically_linked('__eqdf2', 0x8914ee4)
        assert self.out_config.is_statically_linked('__nedf2', 0x8914f74)
        assert self.out_config.is_statically_linked('__gtdf2', 0x8915004)
        assert self.out_config.is_statically_linked('__gedf2', 0x8915088)
        assert self.out_config.is_statically_linked('__ltdf2', 0x891510c)
        assert self.out_config.is_statically_linked('__ledf2', 0x891519c)
        assert self.out_config.is_statically_linked('__floatsidf', 0x891522c)
        assert self.out_config.is_statically_linked('__fixdfsi', 0x89152e0)
        assert self.out_config.is_statically_linked('__truncdfsf2', 0x89153b0)
        assert self.out_config.is_statically_linked('__floatunsidf', 0x8915410)
        assert self.out_config.is_statically_linked('__ucmpdi2', 0x8915504)
        assert self.out_config.is_statically_linked('__make_fp', 0x891554c)
        assert self.out_config.is_statically_linked('__pack_d', 0x8915578)
        assert self.out_config.is_statically_linked('__unpack_d', 0x89158a4)
        assert self.out_config.is_statically_linked('__fpcmp_parts_d', 0x891599c)
        assert self.out_config.is_statically_linked('__pack_f', 0x8915ac8)
        # leftovers - unconfirmed

class Test_2015_X86ClangExe(TestBase):
    settings = TestSettings( input='2015-03-30/ack.x86.clang-3.2.O0.g.ex' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x4010d3:\s*89 10\s*mov dword ptr \[eax\], edx')
        assert self.out_dsm.contains('0x401563:\s*83 ec 1c\s*sub esp, 0x1c')
        assert self.out_dsm.contains('0x40138b:\s*8d 70 01\s*lea esi, \[eax \+ 1\]')

    def test_statically_linked_function_detection(self):
        # confirmed functions
        assert self.out_config.is_statically_linked('___dyn_tls_dtor@12', 0x401690)
        assert self.out_config.is_statically_linked('___dyn_tls_init@12', 0x4016e0)
        assert self.out_config.is_statically_linked('__decode_pointer', 0x401780)
        assert self.out_config.is_statically_linked('_mingw_onexit', 0x4017a0)
        assert self.out_config.is_statically_linked('_atexit', 0x401860)
        assert self.out_config.is_statically_linked('__gnu_exception_handler@4', 0x401880)
        assert self.out_config.is_statically_linked('___mingw_raise_matherr', 0x4019e0)
        assert self.out_config.is_statically_linked('__matherr', 0x401a40)
        assert self.out_config.is_statically_linked('___report_error', 0x401ab0)
        assert self.out_config.is_statically_linked('___write_memory.part.0', 0x401b00)
        assert self.out_config.is_statically_linked('__pei386_runtime_relocator', 0x401d50)
        assert self.out_config.is_statically_linked('__ValidateImageBase', 0x402000)
        assert self.out_config.is_statically_linked('__FindPESection', 0x402030)
        assert self.out_config.is_statically_linked('__FindPESectionByName', 0x402070)
        assert self.out_config.is_statically_linked('___mingw_GetSectionForAddress', 0x402100)
        assert self.out_config.is_statically_linked('___mingw_GetSectionCount', 0x402140)
        assert self.out_config.is_statically_linked('__FindPESectionExec', 0x402170)
        assert self.out_config.is_statically_linked('__GetPEImageBase', 0x4021d0)
        assert self.out_config.is_statically_linked('__IsNonwritableInCurrentImage', 0x402200)
        assert self.out_config.is_statically_linked('___mingw_enum_import_library_names', 0x402250)
        assert self.out_config.is_statically_linked('___mingw_get_msvcrt_handle', 0x4022e0)
        assert self.out_config.is_statically_linked('___do_global_dtors', 0x4023b0)
        assert self.out_config.is_statically_linked('___main', 0x402430)
        assert self.out_config.is_statically_linked('___security_init_cookie', 0x402450)
        assert self.out_config.is_statically_linked('___report_gsfailure', 0x402520)
        assert self.out_config.is_statically_linked('___mingwthr_run_key_dtors.part.0', 0x4025b0)
        assert self.out_config.is_statically_linked('____w64_mingwthr_add_key_dtor', 0x402620)
        assert self.out_config.is_statically_linked('____w64_mingwthr_remove_key_dtor', 0x4026b0)
        assert self.out_config.is_statically_linked('___mingw_TLScallback', 0x402750)
        assert self.out_config.is_statically_linked('__InterlockedCompareExchange', 0x402820)
        assert self.out_config.is_statically_linked('_InterlockedCompareExchange@12', 0x402840)
        assert self.out_config.is_statically_linked('___mingw_fprintf', 0x402860)
        assert self.out_config.is_statically_linked('___mingw_vfprintf', 0x4028a0)
        assert self.out_config.is_statically_linked('___pformat_cvt', 0x4028e0)
        assert self.out_config.is_statically_linked('___pformat_putc', 0x4029e0)
        assert self.out_config.is_statically_linked('___pformat_wputchars', 0x402a40)
        assert self.out_config.is_statically_linked('___pformat_putchars', 0x402b40)
        assert self.out_config.is_statically_linked('___pformat_emit_inf_or_nan', 0x402be0)
        assert self.out_config.is_statically_linked('___pformat_int', 0x402c80)
        assert self.out_config.is_statically_linked('___pformat_xint', 0x402f40)
        assert self.out_config.is_statically_linked('___pformat_emit_radix_point', 0x403250)
        assert self.out_config.is_statically_linked('___pformat_emit_float', 0x403330)
        assert self.out_config.is_statically_linked('___pformat_emit_efloat', 0x403650)
        assert self.out_config.is_statically_linked('___pformat_float', 0x403720)
        assert self.out_config.is_statically_linked('___pformat_gfloat', 0x403800)
        assert self.out_config.is_statically_linked('___pformat_xldouble', 0x403980)
        assert self.out_config.is_statically_linked('___pformat_efloat', 0x403e80)
        assert self.out_config.is_statically_linked('___mingw_pformat', 0x403f30)
        assert self.out_config.is_statically_linked('___gdtoa', 0x404880)
        assert self.out_config.is_statically_linked('___wcrtomb_cp', 0x405e90)
        assert self.out_config.is_statically_linked('_wcrtomb', 0x405f30)
        assert self.out_config.is_statically_linked('_wcsrtombs', 0x405f90)
        assert self.out_config.is_statically_linked('___mbrtowc_cp', 0x406090)
        assert self.out_config.is_statically_linked('_mbrtowc', 0x406230)
        assert self.out_config.is_statically_linked('_mbsrtowcs', 0x4062b0)
        assert self.out_config.is_statically_linked('_mbrlen', 0x4063e0)
        assert self.out_config.is_statically_linked('___rv_alloc_D2A', 0x406440)
        assert self.out_config.is_statically_linked('___nrv_alloc_D2A', 0x406480)
        assert self.out_config.is_statically_linked('___freedtoa', 0x4064d0)
        assert self.out_config.is_statically_linked('___quorem_D2A', 0x4064f0)
        assert self.out_config.is_statically_linked('___mingw_set_output_format', 0x406700)
        assert self.out_config.is_statically_linked('___mingw_get_output_format', 0x406770)
        assert self.out_config.is_statically_linked('_dtoa_lock', 0x4067d0)
        assert self.out_config.is_statically_linked('_dtoa_unlock', 0x406890)
        assert self.out_config.is_statically_linked('_dtoa_lock_cleanup', 0x4068c0)
        assert self.out_config.is_statically_linked('___Balloc_D2A', 0x406900)
        assert self.out_config.is_statically_linked('___Bfree_D2A', 0x4069c0)
        assert self.out_config.is_statically_linked('___multadd_D2A', 0x406a10)
        assert self.out_config.is_statically_linked('___i2b_D2A', 0x406b00)
        assert self.out_config.is_statically_linked('___mult_D2A', 0x406b30)
        assert self.out_config.is_statically_linked('___pow5mult_D2A', 0x406c90)
        assert self.out_config.is_statically_linked('___lshift_D2A', 0x406db0)
        assert self.out_config.is_statically_linked('___cmp_D2A', 0x406ec0)
        assert self.out_config.is_statically_linked('___diff_D2A', 0x406f30)
        assert self.out_config.is_statically_linked('___b2d_D2A', 0x4070c0)
        assert self.out_config.is_statically_linked('___d2b_D2A', 0x4071c0)
        assert self.out_config.is_statically_linked('___strcp_D2A', 0x4072d0)
        assert self.out_config.is_statically_linked('___rshift_D2A', 0x407300)
        assert self.out_config.is_statically_linked('___trailz_D2A', 0x407410)
        assert self.out_config.is_statically_linked('_msvcrt__lc_codepage_func', 0x407450)
        assert self.out_config.is_statically_linked('_setlocale_codepage_hack', 0x407460)
        assert self.out_config.is_statically_linked('_init_codepage_func', 0x4074a0)
        assert self.out_config.is_statically_linked('__umoddi3', 0x407630)
        assert self.out_config.is_statically_linked('__udivdi3', 0x407770)
        # leftovers - unconfirmed
        assert not self.out_config.is_statically_linked('___do_global_ctors', 0x4023e0)

class Test_2015_X86GccExe(TestBase):
    settings = TestSettings( input='2015-03-30/ack.x86.mingw32-gcc-4.7.3.O0.g.ex' )

    def test_check_dsm(self):
        assert self.out_dsm.contains('0x4010ce:\s*a1 cc b1 40 00\s*mov eax, dword ptr \[0x40b1cc\]')
        assert self.out_dsm.contains('0x401123:\s*66 81 fa 0b 02\s*cmp dx, 0x20b')
        assert self.out_dsm.contains('0x4011a0:\s*8d 44 24 1b\s*lea eax, \[esp \+ 0x1b\]')

    def test_unwanted_properties(self):
        assert not self.out_c.contains('int32_t g.*; // ebp') # there should be no work with ebp

    def test_properties(self):
        assert self.out_c.has_comment_matching('// int printf\(const char \* restrict format, ...\);')
        assert self.out_c.has_comment_matching('// int scanf\(const char \* restrict format, ...\);')
        assert self.out_c.contains('int32_t x = 0; // bp-24')
        assert self.out_c.contains('int32_t y = 0; // bp-28')

    def test_statically_linked_function_detection(self):
        # confirmed functions
        assert self.out_config.is_statically_linked('___dyn_tls_dtor@12', 0x401640)
        assert self.out_config.is_statically_linked('___dyn_tls_init@12', 0x401690)
        assert self.out_config.is_statically_linked('__decode_pointer', 0x401730)
        assert self.out_config.is_statically_linked('_mingw_onexit', 0x401750)
        assert self.out_config.is_statically_linked('_atexit', 0x401810)
        assert self.out_config.is_statically_linked('__gnu_exception_handler@4', 0x401830)
        assert self.out_config.is_statically_linked('___mingw_raise_matherr', 0x401990)
        assert self.out_config.is_statically_linked('__matherr', 0x4019f0)
        assert self.out_config.is_statically_linked('___report_error', 0x401a60)
        assert self.out_config.is_statically_linked('___write_memory.part.0', 0x401ab0)
        assert self.out_config.is_statically_linked('__pei386_runtime_relocator', 0x401d00)
        assert self.out_config.is_statically_linked('__ValidateImageBase', 0x401fb0)
        assert self.out_config.is_statically_linked('__FindPESection', 0x401fe0)
        assert self.out_config.is_statically_linked('__FindPESectionByName', 0x402020)
        assert self.out_config.is_statically_linked('___mingw_GetSectionForAddress', 0x4020b0)
        assert self.out_config.is_statically_linked('___mingw_GetSectionCount', 0x4020f0)
        assert self.out_config.is_statically_linked('__FindPESectionExec', 0x402120)
        assert self.out_config.is_statically_linked('__GetPEImageBase', 0x402180)
        assert self.out_config.is_statically_linked('__IsNonwritableInCurrentImage', 0x4021b0)
        assert self.out_config.is_statically_linked('___mingw_enum_import_library_names', 0x402200)
        assert self.out_config.is_statically_linked('___mingw_get_msvcrt_handle', 0x402290)
        assert self.out_config.is_statically_linked('___do_global_dtors', 0x402360)
        assert self.out_config.is_statically_linked('___main', 0x4023e0)
        assert self.out_config.is_statically_linked('___security_init_cookie', 0x402400)
        assert self.out_config.is_statically_linked('___report_gsfailure', 0x4024d0)
        assert self.out_config.is_statically_linked('___mingwthr_run_key_dtors.part.0', 0x402560)
        assert self.out_config.is_statically_linked('____w64_mingwthr_add_key_dtor', 0x4025d0)
        assert self.out_config.is_statically_linked('____w64_mingwthr_remove_key_dtor', 0x402660)
        assert self.out_config.is_statically_linked('___mingw_TLScallback', 0x402700)
        assert self.out_config.is_statically_linked('__InterlockedCompareExchange', 0x4027d0)
        assert self.out_config.is_statically_linked('_InterlockedCompareExchange@12', 0x4027f0)
        assert self.out_config.is_statically_linked('___mingw_fprintf', 0x402810)
        assert self.out_config.is_statically_linked('___mingw_vfprintf', 0x402850)
        assert self.out_config.is_statically_linked('___pformat_cvt', 0x402890)
        assert self.out_config.is_statically_linked('___pformat_putc', 0x402990)
        assert self.out_config.is_statically_linked('___pformat_wputchars', 0x4029f0)
        assert self.out_config.is_statically_linked('___pformat_putchars', 0x402af0)
        assert self.out_config.is_statically_linked('___pformat_emit_inf_or_nan', 0x402b90)
        assert self.out_config.is_statically_linked('___pformat_int', 0x402c30)
        assert self.out_config.is_statically_linked('___pformat_xint', 0x402ef0)
        assert self.out_config.is_statically_linked('___pformat_emit_radix_point', 0x403200)
        assert self.out_config.is_statically_linked('___pformat_emit_float', 0x4032e0)
        assert self.out_config.is_statically_linked('___pformat_emit_efloat', 0x403600)
        assert self.out_config.is_statically_linked('___pformat_float', 0x4036d0)
        assert self.out_config.is_statically_linked('___pformat_gfloat', 0x4037b0)
        assert self.out_config.is_statically_linked('___pformat_xldouble', 0x403930)
        assert self.out_config.is_statically_linked('___pformat_efloat', 0x403e30)
        assert self.out_config.is_statically_linked('___mingw_pformat', 0x403ee0)
        assert self.out_config.is_statically_linked('___gdtoa', 0x404830)
        assert self.out_config.is_statically_linked('___wcrtomb_cp', 0x405e40)
        assert self.out_config.is_statically_linked('_wcrtomb', 0x405ee0)
        assert self.out_config.is_statically_linked('_wcsrtombs', 0x405f40)
        assert self.out_config.is_statically_linked('___mbrtowc_cp', 0x406040)
        assert self.out_config.is_statically_linked('_mbrtowc', 0x4061e0)
        assert self.out_config.is_statically_linked('_mbsrtowcs', 0x406260)
        assert self.out_config.is_statically_linked('_mbrlen', 0x406390)
        assert self.out_config.is_statically_linked('___rv_alloc_D2A', 0x4063f0)
        assert self.out_config.is_statically_linked('___nrv_alloc_D2A', 0x406430)
        assert self.out_config.is_statically_linked('___freedtoa', 0x406480)
        assert self.out_config.is_statically_linked('___quorem_D2A', 0x4064a0)
        assert self.out_config.is_statically_linked('___mingw_set_output_format', 0x4066b0)
        assert self.out_config.is_statically_linked('___mingw_get_output_format', 0x406720)
        assert self.out_config.is_statically_linked('_dtoa_lock', 0x406780)
        assert self.out_config.is_statically_linked('_dtoa_unlock', 0x406840)
        assert self.out_config.is_statically_linked('_dtoa_lock_cleanup', 0x406870)
        assert self.out_config.is_statically_linked('___Balloc_D2A', 0x4068b0)
        assert self.out_config.is_statically_linked('___Bfree_D2A', 0x406970)
        assert self.out_config.is_statically_linked('___multadd_D2A', 0x4069c0)
        assert self.out_config.is_statically_linked('___i2b_D2A', 0x406ab0)
        assert self.out_config.is_statically_linked('___mult_D2A', 0x406ae0)
        assert self.out_config.is_statically_linked('___pow5mult_D2A', 0x406c40)
        assert self.out_config.is_statically_linked('___lshift_D2A', 0x406d60)
        assert self.out_config.is_statically_linked('___cmp_D2A', 0x406e70)
        assert self.out_config.is_statically_linked('___diff_D2A', 0x406ee0)
        assert self.out_config.is_statically_linked('___b2d_D2A', 0x407070)
        assert self.out_config.is_statically_linked('___d2b_D2A', 0x407170)
        assert self.out_config.is_statically_linked('___strcp_D2A', 0x407280)
        assert self.out_config.is_statically_linked('___rshift_D2A', 0x4072b0)
        assert self.out_config.is_statically_linked('___trailz_D2A', 0x4073c0)
        assert self.out_config.is_statically_linked('_msvcrt__lc_codepage_func', 0x407400)
        assert self.out_config.is_statically_linked('_setlocale_codepage_hack', 0x407410)
        assert self.out_config.is_statically_linked('_init_codepage_func', 0x407450)
        assert self.out_config.is_statically_linked('__umoddi3', 0x4075e0)
        assert self.out_config.is_statically_linked('__udivdi3', 0x407720)
        # leftovers - unconfirmed
        assert not self.out_config.is_statically_linked('___do_global_ctors', 0x402390)
