//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2015 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

/* ------- Float Types Definitions ------ */

typedef float float32_t;
typedef double float64_t;

/* -------- Function Prototypes --------- */

int32_t nejaka_funkce(int32_t aa, int32_t bb, char * str, int32_t cc, int32_t dd, int32_t ee);
int32_t smichana_funkce(int32_t xx, float32_t yy, int32_t zz, float64_t dodo);
int32_t volaci_funkce(void);

/* ------------- Functions -------------- */

// From module:   c:\cpp\manyvars\manyvars\windows mobile 6 standard sdk (armv4i)\debug\manyvars.obj
// Address range: 0x11000 - 0x11147
// Line range:    7 - 29
int32_t nejaka_funkce(int32_t aa, int32_t bb, char * str, int32_t cc, int32_t dd, int32_t ee) {
    int32_t v1 = aa + 17 + -3 * bb + cc; // 0x1102c
    int32_t v2 = rand(); // 0x11034
    int32_t v3 = dd + rand(); // 0x11054
    if (ee >= 51) {
        int32_t v4 = 25 * ee - 1250; // 0x11074
        printf("Blabla %d\n", v4);
        v3 += v4;
        // branch -> 0x11098
    }
    // 0x11098
    if (v1 == 0) {
        // 0x110d4
        printf("Vyraz je nulovy a retezec je %s (%d)\n", str, v3);
        // branch -> 0x110e4
    } else {
        // 0x110b8
        printf("Vyraz je nenulovy %d %d\n", v1, v3 + v1);
        // branch -> 0x110e4
    }
    // 0x110e4
    return aa + 23 + bb + v1 + 2 * cc + v2 - v3 + v3 + ee;
}

// From module:   c:\cpp\manyvars\manyvars\windows mobile 6 standard sdk (armv4i)\debug\manyvars.obj
// Address range: 0x11148 - 0x11233
// Line range:    32 - 42
int32_t smichana_funkce(int32_t xx, float32_t yy, int32_t zz, float64_t dodo) {
    // 0x11148
    _stod();
    printf("Hodnota floatu jeje %f\n", (float64_t)(int64_t)(int32_t)yy);
    printf("Soucet je %d\n", zz + xx);
    _muld();
    _itod();
    _addd();
    _dtoi();
    return xx;
}

// From module:   c:\cpp\manyvars\manyvars\windows mobile 6 standard sdk (armv4i)\debug\manyvars.obj
// Address range: 0x11234 - 0x11327
// Line range:    45 - 53
int32_t volaci_funkce(void) {
    int32_t v1 = rand(); // 0x1123c
    _itod();
    _addd();
    _dtos();
    _itod();
    _addd();
    puts("Calling");
    return printf("Vysledek je %d\n", smichana_funkce(v1, (float32_t)v1, 46, (float64_t)(float32_t)v1));
}

// Address range: 0x11328 - 0x114bc
int main(int argc, char ** argv) {
    int32_t v1 = rand(); // 0x11338
    int32_t v2 = rand(); // 0x11348
    int32_t v3 = rand(); // 0x11358
    int32_t v4 = rand(); // 0x11368
    int32_t v5 = rand(); // 0x11378
    int32_t v6 = rand() + v1; // 0x11398
    int32_t v7 = rand(); // 0x113a0
    int32_t v8 = rand(); // 0x113b8
    int32_t v9 = rand(); // 0x113d0
    int32_t v10 = nejaka_funkce(v2, v6, "Retezec", v7 + v2, v3, v5) + v1; // 0x11418
    int32_t result = v4;
    if (v4 < 1001) {
        int32_t v11 = v3 + v2 + v4 - v5 - v6 + v10; // 0x11460
        int32_t v12 = nejaka_funkce(v11, v8 + v3, "Dalsi", v9 + v4, v10, v5); // 0x11488
        volaci_funkce();
        result = v12 + v11;
        // branch -> 0x114ac
    }
    // 0x114ac
    return result;
}

/* --------- External Functions --------- */

// void _addd(void);
// void _dtoi(void);
// void _dtos(void);
// void _itod(void);
// void _muld(void);
// void _stod(void);
// int printf (const char *restrict, ...)
// int puts (const char *)
// int rand ()

/* ---------- Meta-Information ---------- */

// Detected compiler: windows mobile visual c++ 6 standard sdk (armv4i) (visual studio 2008)
// Detected functions: 4 (31 in front-end)
// Decompiler release: jump-table-remove/bd37749-modified (2015-07-19 14:51:18)
// Decompilation date: 2015-06-19 14:51:32
