from regression_tests import *

class Test(Test):
    settings = TestSettings(
        input='dropped.bin'
    )

    def test_check_for_all_currently_detected_strings(self):
        #assert self.out_c.has_string_literal('(null)')
        assert self.out_c.has_string_literal('PST')
        assert self.out_c.has_string_literal('PDT')
        assert self.out_c.has_string_literal('R6002\\r\\n- floating point not loaded\\r\\n')
        assert self.out_c.has_string_literal('%c%c%c%c%c.exe')
        assert self.out_c.has_string_literal('urlmon.dll')
        assert self.out_c.has_string_literal('URLDownloadToFileA')
        assert self.out_c.has_string_literal('open')
        assert self.out_c.has_string_literal('iexplore.exe')
        assert self.out_c.has_string_literal('\\\\%c%c%c%c%c.exe')
        assert self.out_c.has_string_literal('qazwsxedc')
        assert self.out_c.has_string_literal('SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion')
        assert self.out_c.has_string_literal('ProductName')
        assert self.out_c.has_string_literal('2000')
        assert self.out_c.has_string_literal('2003')
        assert self.out_c.has_string_literal('2008')
        assert self.out_c.has_string_literal('HARDWARE\\\\DESCRIPTION\\\\System\\\\CentralProcessor\\\\0')
        assert self.out_c.has_string_literal('ProcessorNameString')
        assert self.out_c.has_string_literal('  | CORE %u ')
        assert self.out_c.has_string_literal('%u MB')
        assert self.out_c.has_string_literal('2014-10')
        assert self.out_c.has_string_literal('\\\\Program Files\\\\Internet Explorer\\\\iexplore.exe')
        assert self.out_c.has_string_literal('0123456789abcdefghijklmnopqrstuvwxyz')
        assert self.out_c.has_string_literal('%s/%s')
        assert self.out_c.has_string_literal('#0%s!')
        #assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nAccept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*\\r\\nAccept-Language: en-us\\r\\nAccept-Encoding: gzip, deflate\\r\\nUser-Agent:Mozilla/4.0 (compatible; MSIE %d.0; Windows NT %d.1; SV1)\\r\\nHost: %s\\r\\nConnection: Keep-Alive\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nAccept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*\\r\\nAccept-Language: en-us\\r\\nAccept-Encoding: gzip, deflate\\r\\nUser-Agent:Mozilla/4.0 (compatible; MSIE %d.0; Windows NT %d.1; SV1)\\r\\nHost: %s:%d\\r\\nConnection: Keep-Alive\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nContent-Type: text/html\\r\\nHost: %s\\r\\nAccept: text/html, */*\\r\\nUser-Agent:Mozilla/5.0 (X11; U; Linux i686; en-US; re:1.4.0) Gecko/20080808 Firefox/%d.0\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nReferer: http://%s:80/http://%s\\r\\nHost: %s\\r\\nConnection: Close\\r\\nCache-Control: no-cache\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('%s %s%s')
        #assert self.out_c.has_string_literal('GET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htmGET ^&&%$%$^%$#^&**(*((&*^%$##$%^&*(*&^%$%^&*.htm')
        #assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nHost: %s\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nHost: %s:%d\\r\\n\\r\\n')
        #assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nContent-Type: text/html\\r\\nHost: %s\\r\\nAccept: text/html, */*\\r\\nUser-Agent:Mozilla/4.0 (compatible; MSIE %d.00; Windows NT %d.0; MyIE 3.01)\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nContent-Type: text/html\\r\\nHost: %s:%d\\r\\nAccept: text/html, */*\\r\\nUser-Agent:Mozilla/4.0 (compatible; MSIE %d.00; Windows NT %d.0; MyIE 3.01)\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('GET %s HTTP/1.1\\r\\nAccept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/x-shockwave-flash, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*\\r\\nAccept-Language: en-us\\r\\nAccept-Encoding: gzip, deflate\\r\\nUser-Agent:Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)\\r\\nHost: %s\\r\\nConnection: Keep-Alive\\r\\n\\r\\n')
        assert self.out_c.has_string_literal('192.168.1.244')
        assert self.out_c.has_string_literal('%d.%d.%d.%d')
        assert self.out_c.has_string_literal('TZ')
        assert self.out_c.has_string_literal('<program name unknown>')
        assert self.out_c.has_string_literal('Runtime Error!\\n\\nProgram: ')
        assert self.out_c.has_string_literal('\\n\\n')
        assert self.out_c.has_string_literal('Microsoft Visual C++ Runtime Library')
        assert self.out_c.has_string_literal('...')
        assert self.out_c.has_string_literal('user32.dll')
        assert self.out_c.has_string_literal('MessageBoxA')
        assert self.out_c.has_string_literal('GetActiveWindow')
        assert self.out_c.has_string_literal('GetLastActivePopup')
